version: '2'
services:
  
  proxy:
    build: Proxy
    ports:
      - "80:80s"
    depends_on :
      - static
  static:
    build: Nginx
  flask:
    build: Flask
    depends_on:
     - redis
     - static
  redis:
    image: redis
  
